version: 2
updates:
  - package-ecosystem: npm
    directory: /typescript
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: /python
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
